#!/usr/bin/env python3
"""X11 75dpi Helvetica 10 (dialogs) and bold 12 (system font) (Adobe/DEC, X11 license) -> port/font_gen.h.
Stands in for MS Sans Serif 8pt. Glyphs 32..255 as 1-bit rows."""
import gzip, os
from PIL import PcfFontFile, ImageFont, Image, ImageDraw
out = ['// generated by port/mkfont.py from X11 helvR10/helvB12 - do not edit']
for name, var, LH in (('helvR10', 'normal', 13), ('helvB12', 'bold', 16)):
    # save in a child process: loading in the same process gave solid boxes
    import subprocess, sys, tempfile
    tmp = os.path.join(tempfile.gettempdir(), 'decker_' + name)
    subprocess.run([sys.executable, '-c', f"import gzip; from PIL import PcfFontFile; PcfFontFile.PcfFontFile(gzip.open('/opt/X11/share/fonts/75dpi/{name}.pcf.gz')).save('{tmp}')"], check=True)
    font = ImageFont.load(tmp + '.pil')
    H = 24
    imgs, widths = [], []
    for c in range(32, 256):
        ch = bytes([c]).decode('latin-1')
        w = int(font.getlength(ch)) if c != 32 else 4
        im = Image.new('L', (max(w, 1) + 4, H), 255)
        ImageDraw.Draw(im).text((0, 4), ch, font=font, fill=0)
        widths.append(w)
        rows = []
        for y in range(H):
            bits = 0
            for x in range(min(im.width, 16)):
                if im.getpixel((x, y)) < 128: bits |= 1 << x
            rows.append(bits)
        imgs.append(rows)
    # vertical extent actually used by ASCII letters
    used = [y for rows in imgs[:95] for y, b in enumerate(rows) if b]
    top, bot = min(used), max(used)
    # pad to the Windows line height (MS Sans Serif 8 = 13, System = 16)
    top -= (LH - (bot - top + 1)) // 2
    bot = top + LH - 1
    out.append(f'static const int font_{var}_height = {bot - top + 1};')
    out.append(f'static const unsigned char font_{var}_width[224] = {{{",".join(map(str, widths))}}};')
    out.append(f'static const unsigned short font_{var}_rows[224][{bot - top + 1}] = {{')
    for rows in imgs:
        out.append('{' + ','.join(str(r) for r in rows[top:bot + 1]) + '},')
    out.append('};')
open(os.path.join(os.path.dirname(__file__), 'font_gen.h'), 'w').write('\n'.join(out) + '\n')
