#!/usr/bin/env python3
"""Decker.rc -> port/res_gen.cpp: dialog templates, bitmaps, accelerators,
string table, menus and combo box DLGINIT strings for the MFC shim."""
import re, sys, os

src = open(os.path.join(os.path.dirname(__file__), '..', 'Decker.rc'), encoding='latin-1').read().replace('\r', '')
# join continuation lines (lines ending with | or ,)
lines = []
for l in src.split('\n'):
    if lines and re.search(r'[|,]\s*$', lines[-1]):
        lines[-1] = lines[-1].rstrip() + ' ' + l.strip()
    else:
        lines.append(l)

def cstr(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

def split_args(s):
    out, cur, q = [], '', False
    i = 0
    while i < len(s):
        c = s[i]
        if c == '"':
            if q and i + 1 < len(s) and s[i+1] == '"':
                cur += '"'; i += 2; continue
            q = not q
            cur += c
        elif c == ',' and not q:
            out.append(cur.strip()); cur = ''
        else:
            cur += c
        i += 1
    if cur.strip():
        out.append(cur.strip())
    return out

def unq(s):
    s = s.strip()
    if s.startswith('"'):
        return s[1:-1].replace('\\n', '\n').replace('\\t', '\t')
    return s

def expr(s):
    return '(' + s.replace('|', ' | ') + ')' if s else '0'

defaults = {
    'LTEXT': ('Static', 'SS_LEFT|WS_GROUP'), 'RTEXT': ('Static', 'SS_RIGHT|WS_GROUP'),
    'CTEXT': ('Static', 'SS_CENTER|WS_GROUP'),
    'PUSHBUTTON': ('Button', 'BS_PUSHBUTTON|WS_TABSTOP'),
    'DEFPUSHBUTTON': ('Button', 'BS_DEFPUSHBUTTON|WS_TABSTOP'),
    'GROUPBOX': ('Button', 'BS_GROUPBOX'),
    'EDITTEXT': ('Edit', 'ES_LEFT|WS_BORDER|WS_TABSTOP'),
    'COMBOBOX': ('ComboBox', 'CBS_DROPDOWN'),
    'LISTBOX': ('ListBox', 'LBS_NOTIFY|WS_BORDER'),
}

out = ['// generated by port/rc2res.py from Decker.rc - do not edit',
       '#include "stdafx.h"', '#include "resource.h"', '#include "port/res.h"', '']
dialogs, bitmaps, accels, strings, menus, dlginit = [], [], [], [], [], {}

i = 0
while i < len(lines):
    l = lines[i]
    m = re.match(r'^(\w+)\s+DIALOG(?:EX)?\s+(?:DISCARDABLE\s+)?(\d+),\s*(\d+),\s*(\d+),\s*(\d+)', l)
    if m:
        name, cx, cy = m.group(1), m.group(4), m.group(5)
        caption, style, items = '', '0', []
        i += 1
        while not lines[i].startswith('BEGIN'):
            h = lines[i]
            if h.startswith('CAPTION'):
                caption = unq(h[7:])
            elif h.startswith('STYLE'):
                style = expr(h[5:].strip())
            i += 1
        i += 1
        while not lines[i].startswith('END'):
            h = lines[i].strip()
            kw = h.split(None, 1)[0]
            args = split_args(h[len(kw):])
            if kw == 'CONTROL':
                text, cid, cls, st = unq(args[0]), args[1], unq(args[2]), args[3]
                x, y, w, hh = args[4:8]
                ex = args[8] if len(args) > 8 else '0'
                st = 'WS_CHILD|WS_VISIBLE|' + st
            else:
                cls, dst = defaults[kw]
                if kw in ('EDITTEXT', 'COMBOBOX', 'LISTBOX'):
                    text, rest = '', args
                else:
                    text, rest = unq(args[0]), args[1:]
                cid, x, y, w, hh = rest[:5]
                st = 'WS_CHILD|WS_VISIBLE|' + dst + ('|' + rest[5] if len(rest) > 5 else '')
                ex = rest[6] if len(rest) > 6 else '0'
            items.append(f'  {{{cstr(cls)}, {cstr(text)}, {cid}, {x}, {y}, {w}, {hh}, (DWORD){expr(st)}, (DWORD){expr(ex)}}},')
            i += 1
        out.append(f'static const DlgItem dlg_{name}[] = {{')
        out += items
        out.append('};')
        dialogs.append(f'  {{{name}, {cx}, {cy}, {cstr(caption)}, (DWORD){style}, dlg_{name}, {len(items)}}},')
        i += 1
        continue
    m = re.match(r'^(\w+)\s+BITMAP\s+(?:DISCARDABLE\s+)?"(.*)"', l)
    if m:
        bitmaps.append(f'  {{{m.group(1)}, {cstr(m.group(2).replace(chr(92)*2, "/"))}}},')
    m = re.match(r'^(\w+)\s+ACCELERATORS', l)
    if m:
        i += 2
        while not lines[i].startswith('END'):
            a = split_args(lines[i])
            key = a[0]
            if key.startswith('"'):
                key = str(ord(unq(key)))
            flags = ' | '.join('FCONTROL' if f == 'CONTROL' else 'FSHIFT' if f == 'SHIFT' else 'FALT' if f == 'ALT' else '0' for f in a[2:])
            accels.append(f'  {{{m.group(1)}, {key}, {a[1]}, {flags or 0}}},')
            i += 1
    if l.startswith('STRINGTABLE'):
        i += 2
        while not lines[i].startswith('END'):
            mm = re.match(r'\s*(\w+)\s+(".*")', lines[i])
            if mm:
                strings.append(f'  {{{mm.group(1)}, {cstr(unq(mm.group(2)))}}},')
            i += 1
    m = re.match(r'^(\w+)\s+MENU', l)
    if m:
        while not lines[i].strip().startswith('END'):
            mm = re.match(r'\s*MENUITEM\s+"(.*)",\s*(\w+)', lines[i])
            if mm:
                menus.append(f'  {{{m.group(1)}, {cstr(mm.group(1))}, {mm.group(2)}}},')
            i += 1
    m = re.match(r'^(\w+)\s+DLGINIT', l)
    if m:
        i += 2
        block = ''
        while not lines[i].startswith('END'):
            block += ' ' + lines[i].strip() + ','
            i += 1
        toks = [t for t in split_args(block) if t]
        k, cur, data = 0, None, b''
        while k < len(toks):
            t = toks[k]
            if re.match(r'^[A-Za-z_]\w*$', t):
                if cur: dlginit.setdefault((m.group(1), cur), []).append(data.split(b'\0')[0].decode('latin-1'))
                cur, data = t, b''
                k += 4; continue
            if t.startswith('0x'):
                v = int(t, 16); data += bytes([v & 255, v >> 8])
            elif t.startswith('"'):
                data += b'\0'
            k += 1
        if cur: dlginit.setdefault((m.group(1), cur), []).append(data.split(b'\0')[0].decode('latin-1'))
    i += 1

out.append('const DlgTemplate g_dlgTemplates[] = {'); out += dialogs; out.append('  {0,0,0,0,0,0,0}};')
out.append('const BitmapRes g_bitmapRes[] = {'); out += bitmaps; out.append('  {0,0}};')
out.append('const AccelRes g_accelRes[] = {'); out += accels; out.append('  {0,0,0,0}};')
out.append('const StringRes g_stringRes[] = {'); out += strings; out.append('  {0,0}};')
out.append('const MenuRes g_menuRes[] = {'); out += menus; out.append('  {0,0,0}};')
out.append('const DlgInitRes g_dlgInitRes[] = {')
for (dlg, cid), vals in dlginit.items():
    for v in vals:
        out.append(f'  {{{dlg}, {cid}, {cstr(v)}}},')
out.append('  {0,0,0}};')
open(os.path.join(os.path.dirname(__file__), 'res_gen.cpp'), 'w').write('\n'.join(out) + '\n')
